### ISSUE TITLE
`fileNode` and `text/markdown` mappings 

### ISSUE THREAD

**Issue by mmcc** [jbolda/gatsby-source-airtable#41]
Thank you so much for such a useful source plugin! I seem to be running into an issue with combining `text/markdown` and `fileNode` in the same `mapping` key on a table. If I just use one or the other, things work as expected, so I could theoretically just use a markdown component and have the markdown fields be text, but this feels like it should work. If I use both together, I get an error like this:

```
AirtableField.raw:
 - type: array<object>
   value: [ { id: 'attK6ZPYWYZPEI9Ut', url: 'https://dl.airtable.com/.attachments/6bdc2db7bea5ca8572a8fa4e74e1c656/3c5578
7f/some-image.png', filename: 'some-image.png', size: 65808, type: 'image/png', thumbnails: [Object] } ]  
 - type: string
   value: 'Wow, such cms. *Wow*. It\'s a thing.'  
```

I'm sure you can guess which field is which 😂 Is there something special I need to do to account for both or have I stumbled across a bug? I haven't tried putting the two fields in _different_ tables for whatever that's worth.

Edit: Including the config in case that's useful:

```javascript
    {
      resolve: 'gatsby-source-airtable',
      options: {
        tables: [
          {
            baseId: 'asdfasdf',
            tableName: 'Foo',
            mapping: { Description: 'text/markdown', Banner: 'fileNode' },
          },
        ],
      },
    },
```

**Comment by jbolda** [comment]
Huh. That smells like bug to me. We haven't tested that in any of the example (and I haven't tried that before). From the looks of it, that is a Gatsby core error saying that the [`raw`](https://github.com/jbolda/gatsby-source-airtable/blob/master/gatsby-node.js#L317) property on type [`AirtableField`](https://github.com/jbolda/gatsby-source-airtable/blob/master/gatsby-node.js#L319) has two different types. That is probably a newer added error message that is just bringing up something that was always an error, but just silently failed/assumed a type.

I think it is a similar issue to #25 except on `AirtableField` (lower level fields that were mapped) instead of on the main `Airtable` node. Would you be able to investigate further? (Assuming I am making any sense, hah.)

**Comment by mmcc** [comment]
Ah yep, I also came across #25 when trying to figure out if this was a known issue or not. I'm only just starting to really dig past the basics of GraphQL and source plugins for Gatsby, so I'm fumbling around a little bit trying to investigate, but I'll dig in as much as I can!

**Comment by jbolda** [comment]
We have published a beta version of `2.1.0` which should have this functionality. Please give it a shot! I am going to close this, but feel free to reopen if anything comes up.

**Comment by akiarostami** [comment]
I am still seeing this issue, on exactly the same setup. This is what I have in my airtable_options:

```
mapping: {
    image: 'fileNode',
    desc: 'text/markdown',
},
```

and this is the error I'm seeing:

```
AirtableField.raw:
 - type: array
   value: [ ..., { id: 'atte2xZRBwvF4U3UI', url: 'https://dl.airtable.com/.attachments/746a07721477d9cd1e54d05a9ab60856/0d3929eb/picture.jpg', filename:
'picture.jpg', size: 138519, type: 'image/jpeg', thumbnails: [Object] }, ... ]
 - type: string
   value: 'Welcome to out blog.\n'
```
